### ISSUE TITLE
Issue running example locally

### ISSUE THREAD

**Issue by HAZARDU5** [haydenjameslee/networked-aframe#10]
I'm getting the following error in the browser console when running the example locally using `npm start` then access it at [http://MY_LOCAL_IP_ADDRESS:8080/basic.html](http://MY_LOCAL_IP_ADDRESS:8080/basic.html):

Chrome:

```
build.js:2539 NOVIABLEICE No usable STUN/TURN path
(anonymous) @ build.js:2539
```

Firefox:

```
RTCIceServer.url is deprecated! Use urls instead. easyrtc.js:3587
onaddstream is deprecated! Use peerConnection.ontrack instead.  easyrtc.js:6356
RTCIceServer.url is deprecated! Use urls instead. easyrtc.js:3587
onaddstream is deprecated! Use peerConnection.ontrack instead.  easyrtc.js:6356
ICE failed, see about:webrtc for more details
```

Seems like easyrtc can't connect to the google stun servers correctly. Do you know what could be causing this? I'm running the browser on the same machine as the server.

It happens in the latest production version of Firefox and Chrome.

**Comment by haydenjameslee** [comment]
I have not seen that error before when both clients are on the same machine. I have seen it quite often on mobile networks however. What happens if you try to access the examples at https://haydenlee.io/networked-aframe/basic.html with two tabs on the same PC?

**Comment by HAZARDU5** [comment]
The example works, but in my case the server and both clients are all running on the same machine. I'll look into this further tonight to see if I can get a clearer picture as to what is going on.

**Comment by HAZARDU5** [comment]
Still no luck, even with running the `basic.html` example at the latest commit `e2e59e46c07b3e5eb261b0602c9516af70ed26a5`. What browser are you using when developing locally?

**Comment by HAZARDU5** [comment]
I think we can close this off for now. I will re-test in v2.0 and see if it's still  a problem.
