### ISSUE TITLE
How to get all connected players list

### ISSUE THREAD

**Issue by gftruj** [haydenjameslee/networked-aframe#19]
Hello, 
I'm trying to get a list/array of all players ( player +naf-xxxxxx entities) 
I found a list in `NAF.entities.entities`, but I'm unable to get them when i try to log it in the console, for I only get one reference.

Is there a method i missed, or does it need to be implemented ?

**Comment by haydenjameslee** [comment]
The naf-xxxx entities are the networked entities which is different from the list of connected clients. This is going to change a lot soon but try `NAF.connection.connectList`
