### ISSUE TITLE
Mobile Clients not visible

### ISSUE THREAD

**Issue by karunakaruna** [haydenjameslee/networked-aframe#2]
Potentially when using HTTPS for signallingURL.

Desktop clients show:
Successfully started datachannel to  Ao5IrnsQKoP2niV5
Opened data channel from Ao5IrnsQKoP2niV5
...
Closed data channel from Ao5IrnsQKoP2niV5

Mobile clients show only:
Closed data channel from Ao5IrnsQKoP2niV5

**Comment by haydenjameslee** [comment]
This was using the example demos (from private convo).

Would be good to repro locally using localhost. I'll try in the next day or two, if somebody else wants to try go ahead. You'll need to change the signalling URL to the local IP of your PC and then connect directly to that IP with your phone.

**Comment by haydenjameslee** [comment]
I tried to repro just now. It was working fine for me on mobile and using https://glitch.com/~networked-aframe to test. There may have been one time when this error occurred but I can't confirm that.

**Comment by kfarr** [comment]
To provide a device test data point, I wasn't able to get local or remote demos working with iOS 10.3.2 Beta 4 Safari. I can get both demos working open in separate tabs on desktop PC Chrome. I was able to get Android Chrome (Samsung Galaxy S7 Chrome, not webvr) browser to broadcast avatar position to the desktop during one session, but took a few tries on both the desktop and mobile browser to get this to work.

Does iOS support webrtc at all? Looks like not: http://iswebrtcreadyyet.com/

For remote demo I'm using [glitch.io demo](https://networked-aframe.glitch.me/). For local demos I am [following this tutorial](https://github.com/haydenjameslee/networked-aframe/blob/master/docs/Tutorial:%20Create%20your%20first%20Networked-Aframe%20experience.md).

**Comment by haydenjameslee** [comment]
This is most likely due to webrtc not being supported on iOS.

I'll be making a switch in an upcoming release which lets you use socket.io for all networking, instead of WebRTC. This will work on iOS and avoid any of the problems with establishing P2P connections.

**Comment by brendanluu** [comment]
Yes! iOS support with socket.io would be very useful

**Comment by haydenjameslee** [comment]
@brendanluu Cool i'll probably just hack together a quick option and add it in the next release (which also features hand controller support)

**Comment by haydenjameslee** [comment]
@brendanluu in NAF 0.2.0 all messages get sent across socket.io by default. WebRTC is now optional.

**Comment by Vamoss** [comment]
Hi @haydenjameslee, I am trying to make the basic-audio example work on the iPhone, I also tried to change the 'adapter' to use 'easyrtc', but it gets a Websocket error:
`WebSocket network error: The operation couldn’t be completed. (OSStatus error -9807.)`

It is working good on windows, mac, ubuntu and android.
Do you know what I can be possibly doing wrong?

**Comment by Vamoss** [comment]
I guess I changed it in the wrong place. Is it right?
network-scene.js, line 10:
`adapter: {default: 'easyrtc'},`

**Comment by Vamoss** [comment]
I saw, it meant to be in the basic-audio.html, line 41:
`adapter: wseasyrtc;`

Using `wseasyrtc` makes the iPhone see the other players, but no audio.
`easyrtc`, no audio and no players.

**Comment by haydenjameslee** [comment]
@vamoss could you open another GitHub issue for this new problem?
