### ISSUE TITLE
is there a raw three.js support

### ISSUE THREAD

**Issue by jeromeetienne** [haydenjameslee/networked-aframe#20]
it could be useful, thus application in aframe and in three.js could communicate together

I think it makes sense because is a network library

**Comment by haydenjameslee** [comment]
I haven't looked into implementing anything like that, but check out @takahirox's project: https://github.com/takahirox/ThreeNetwork

**Comment by jeromeetienne** [comment]
Thanks for the suggestino but i would loose the networked-aframe compatibility, and his code is more a bunch of hackish experiment than a polished library.

This was just an idea i had. so If you ever want to do it, you got my support :)

Keep on the good work :)

**Comment by takahirox** [comment]
Just curious to know what you mean by "his code is more a bunch of hackish experiment than a polished library"

**Comment by jeromeetienne** [comment]
oh sorry didnt want to start a polemic nor to offende anyone. i did a mistake when looking at your repository. i overlooked the ```js/``` repository. where all the code is.

i feel bad now :(

let me edit this comment
