### ISSUE TITLE
Lerping is broken in A-Frame 0.6.0

### ISSUE THREAD

**Issue by haydenjameslee** [haydenjameslee/networked-aframe#21]
Waiting for A-Frame 0.6.1 which should fix this

**Comment by intensr** [comment]
is this the reason for unstable streams as such ?
![image](https://user-images.githubusercontent.com/6901764/28066242-77c476da-663c-11e7-9ffa-6bfebc16a4cd.png)

**Comment by haydenjameslee** [comment]
No that is a different problem that I'm not aware of. If you could make another issue for it that'd be great.

**Comment by haydenjameslee** [comment]
https://github.com/aframevr/aframe/issues/2829

**Comment by haydenjameslee** [comment]
Turns out there was another change in A-Frame 0.6.0 related to the `componentchanged` event being throttled that broke lerping as well. This has been fixed now: https://github.com/haydenjameslee/networked-aframe/pull/31
