### ISSUE TITLE
Questions to use it in Augmented Reality

### ISSUE THREAD

**Issue by jeromeetienne** [haydenjameslee/networked-aframe#3]
I love what you did, the easyness of it is so nice!

i would love to use that in augmented reality (with [ar.js](https://github.com/jeromeetienne/ar.js)) but for that i need to change the usual behavior a bit, so i have 2 questions :)

1. i would like to get the avatar, not attached to the camera, but somewhere above the marker. Where should i look to see how to change avatar position.
2. i would like to move the avatar according to controls on a phone, so some kind of touchscreen joystick. Where should i look to be able to controls the position of the avatar from javascript ?

Thanks :)

**Comment by haydenjameslee** [comment]
Thanks!

@jeromeetienne ar.js looked great. It'd be awesome to have an official example that shows NAF can work well for AR.

If i'm understanding you right you're wanting an avatar that is completely independent of the camera. That's totally possible, you'll just think of the object as a regular network entity, and then enable the controls for the local user.

Something like this should work:

```javascript
var avatar = NAF.entities.createNetworkEntity("ar-avatar", position, rotation);

avatar.SetAttribute("gamepad-controls","lookEnabled: false");
```

and then include donmccurdy's gamepad-controls component: https://github.com/donmccurdy/aframe-gamepad-controls

Let me know if that works!

**Comment by jeromeetienne** [comment]
excelent! i love the idea of the official example. i will try and keep you updated :)

**Comment by haydenjameslee** [comment]
Closing this for now. Feel free to post further questions here though!
