### ISSUE TITLE
Not able to install in my system.

### ISSUE THREAD

**Issue by rajababu3** [haydenjameslee/networked-aframe#38]
- 0 info it worked if it ends with ok
- 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
- 2 info using npm@5.4.1
- 3 info using node@v8.4.0
- 4 verbose run-script [ 'predev', 'dev', 'postdev' ]
- 5 info lifecycle networked-aframe@0.2.3~predev: networked-aframe@0.2.3
- 6 info lifecycle networked-aframe@0.2.3~dev: networked-aframe@0.2.3
- 7 verbose lifecycle networked-aframe@0.2.3~dev: unsafe-perm in lifecycle true
- 8 verbose lifecycle networked-aframe@0.2.3~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/rajababu/rb/aframe/networked-aframe/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/rajababu/PycharmProjects/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/rajababu/anaconda/bin
- 9 verbose lifecycle networked-aframe@0.2.3~dev: CWD: /Users/rajababu/rb/aframe/networked-aframe
- 10 silly lifecycle networked-aframe@0.2.3~dev: Args: [ '-c', 'npm run build && node ./server/server.js' ]
- 11 silly lifecycle networked-aframe@0.2.3~dev: Returned: code: 1  signal: null
- 12 info lifecycle networked-aframe@0.2.3~dev: Failed to exec dev script
- 13 verbose stack Error: networked-aframe@0.2.3 dev: `npm run build && node ./server/server.js`
- 13 verbose stack Exit status 1
- 13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
- 13 verbose stack     at emitTwo (events.js:125:13)
- 13 verbose stack     at EventEmitter.emit (events.js:213:7)
- 13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
- 13 verbose stack     at emitTwo (events.js:125:13)
- 13 verbose stack     at ChildProcess.emit (events.js:213:7)
- 13 verbose stack     at maybeClose (internal/child_process.js:927:16)
- 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
- 14 verbose pkgid networked-aframe@0.2.3
- 15 verbose cwd /Users/rajababu/rb/aframe/networked-aframe
- 16 verbose Darwin 16.7.0
- 17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
- 18 verbose node v8.4.0
- 19 verbose npm  v5.4.1
- 20 error code ELIFECYCLE
- 21 error errno 1
- 22 error networked-aframe@0.2.3 dev: `npm run build && node ./server/server.js`
- 22 error Exit status 1
- 23 error Failed at the networked-aframe@0.2.3 dev script.
- 23 error This is probably not a problem with npm. There is likely additional logging output above.
- 24 verbose exit [ 1, true ]

**Comment by rajababu3** [comment]
Solved!

**Comment by haydenjameslee** [comment]
It would be great if you could explain how you solved it so other people can learn from it :)
