### ISSUE TITLE
easyrtc with audio doesnt work consistantly in Chrome

### ISSUE THREAD

**Issue by greengiant83** [haydenjameslee/networked-aframe#44]
I am using the basic example from the tutorial with adapter changed to easyrtc and audio turned on

`<a-scene networked-scene="
      room: dev;
      debug: true;
      adapter: easyrtc;
      audio: true;
    ">`

When hosting the server locally and testing in Chrome (v61.0.3163.100 64bit) a new tab joining an existing room will not see the existing occupants of the room, but the existing tabs will see the new comers. Audio is never present

Works as expected consistently in Firefox

**Comment by machenmusik** [comment]
My understanding is that audio uses WebRTC, which for privacy reasons Chrome requires that the page be served over https.

**Comment by haydenjameslee** [comment]
@machenmusik is correct.

https://developers.google.com/web/updates/2015/10/chrome-47-webrtc

> Starting with Chrome 47, getUserMedia() requests are only allowed from secure origins: HTTPS or localhost

Here is an example over HTTPS that is working as expected: https://glitch.com/edit/#!/political-reaction?path=public/index.html:33:8

**Comment by greengiant83** [comment]
That may be. It was my understanding that localhost domains were given an exception to make development easier. In any case, I have it hosted on heroku and accessed with https and I see the same behavior. It seems as though if the server has been sitting idle for a while, the first two instances will work, but subsequent refreshes and new tabs will have the described behavior

https://vrchat.herokuapp.com/basic.html

**Comment by haydenjameslee** [comment]
Oh I misread the OP comment. Yes you are right that Chrome makes an exception for localhost. Sounds like there may be a race condition causing this. 

Does the avatar appear after you have moved it at all? 

Are you testing with two tabs and switching between the two? Or do you have the two tabs in separate windows that are both visible at the same time?

**Comment by greengiant83** [comment]
The avatar does not show up after movement (from either tab). I have two tabs open with each on its own monitor so I can see them at the same time.

**Comment by haydenjameslee** [comment]
If audio is set to false does it work every time?

**Comment by greengiant83** [comment]
I just checked, but sadly I still see the same behavior

**Comment by greengiant83** [comment]
Is this just me? Is there a hosted implementation somewhere that uses the easyrtc adapter that I could check?

**Comment by machenmusik** [comment]
Maybe try the Glitch @haydenjameslee mentioned above?
https://glitch.com/edit/#!/political-reaction?path=public/index.html:33:8
Or just to use, not to look at code:
https://political-reaction.glitch.me

**Comment by greengiant83** [comment]
Doh. I am idiot, I stopped reading that post when I saw that it was about https because I had already tried it and totally missed the glitch link. My apologies.

It does not work for me either. Same behavior. No audio, and the most recent fellow can't see the existing occupants

**Comment by machenmusik** [comment]
Are you on an open direct Internet connection?  If you are in public wifi, corporate IT, or other controlled network they may be blocking WebRTC traffic

**Comment by greengiant83** [comment]
I have tried this from home (behind a router) and the office (behind god knows what). I can say that the traffic is not being blocked because this works fine in Firefox on the same machine on the same network

**Comment by haydenjameslee** [comment]
If you change the adapter to `wseasyrtc` do you ever see the error?

If not, we've pretty much narrowed it down to either a bug with easyrtc (but you'd expect to see that happening to other people too) or a difference with how Mozilla and Chrome manage WebRTC connections, most likely related to the ICE process.

To see if using STUN/TURN server would solve the webrtc problem, add this to networked-scene:
`serverURL: https://haydenlee.io;`

That'll use my server for the connection process, and I've setup XirSys on that server. Fingers crossed that works.

**Comment by greengiant83** [comment]
I am very sorry, guys. I have sent us on a wild goose chase. 

I tried the app in an Chrome Incognito window and that worked fine. This got me thinking maybe it was one of my extensions was messing with things. The chrome extension, Privacy Badger, was responsible for the problems I described. I had disabled it using its UI for my sight, so I hadnt really considered it in the mix. Disabling it chrome://extensions/ completely pulls it out of the picture.

Please accept my apologies for wasting so much of your time.

**Comment by haydenjameslee** [comment]
Oh cool! That's really good to know. Thanks for continuing to look into it.
