### ISSUE TITLE
Allow changing of server port number

### ISSUE THREAD

**Issue by patcat** [haydenjameslee/networked-aframe#5]
This is more of a feature request — it'd be great to be able to change the port number that it runs on. e.g. rather than localhost:8080, to override it via the npm command to run on 5000?

Not sure if that would mess anything else up in the app, but it could be handy for those running a bunch of Node servers at once.

**Comment by haydenjameslee** [comment]
Agreed. I'll add it in the next release.

**Comment by haydenjameslee** [comment]
Added in https://github.com/haydenjameslee/networked-aframe/commit/d9217ca1309c964b1b3abc5946c2fcb89c2bf785

For example, to specify port 5000:

`PORT=5000 npm start`

**Comment by patcat** [comment]
@haydenjameslee I can confirm, this works wonderfully!

On PC to change the environment variable, it's like so:

`set PORT=5000`
followed by
`npm start`

Nice work!
