### ISSUE TITLE
mobile performance killer: consider removing particles

### ISSUE THREAD

**Issue by caseyyee** [haydenjameslee/networked-aframe#6]
https://github.com/haydenjameslee/networked-aframe/blob/master/server/static/basic.html#L115

The particle effects causes major performance issues on mobile using the Google Pixel running Chrome Canary.  I would remove this.

Not sure if anyone else is experiencing issues, or if it's just me.

**Comment by haydenjameslee** [comment]
Great idea. Will look into this.

**Comment by haydenjameslee** [comment]
Done: https://github.com/haydenjameslee/networked-aframe/commit/6c5b5068d33b1fd4806fcb9cd927813da7d439b3
