### ISSUE TITLE
Not seeing the other avatar in Basic.html in two separate windows

### ISSUE THREAD

**Issue by dilanshah** [haydenjameslee/networked-aframe#8]
At the step in [Hayden's Tutorial](https://github.com/haydenjameslee/networked-aframe/blob/master/docs/Tutorial:%20Create%20your%20first%20Networked-Aframe%20experience.md) in which you can fire two browser windows up with the same example and expect to see a similar outcome to the gif included--I didn't find the same result. 

Both set to basic.html with Chrome Version 56.0.2924.87 (64-bit)

**Comment by haydenjameslee** [comment]
Could you post the logs of the browser's developer logs and the NodeJS console where you ran npm start?

**Comment by dilanshah** [comment]
This is the text file from my terminal.
[nodejs-terminal.txt](https://github.com/haydenjameslee/networked-aframe/files/859834/nodejs-terminal.txt)
I've messaged you on A-Frame slack with a clarifying question about how to post the rest of the requested info.

**Comment by haydenjameslee** [comment]
The nodejs-terminal.txt looks correct.

Pasting the other logs you sent via DM:

```basic.html:6 GET http://localhost:8080/build.js 
index.js:73 A-Frame Version: 0.5.0 (Date 10-02-2017, Commit #110055d)
index.js:74 three Version: ^0.83.0
index.js:75 WebVR Polyfill Version: dmarcos/webvr-polyfill#a02a8089b
basic.html:6 GET http://localhost:8080/build.js 
basic.html:30 Uncaught ReferenceError: NAF is not defined
    at basic.html:30
(anonymous) @ basic.html:30
browser.js:117 core:propertyTypes:warn `src` property type is deprecated. Use `asset` instead. +0ms
three.js:19590 THREE.WebGLRenderer 83```

It shouldn't be using `build.js`. Replace that line of code with this one:

```html
<script src="https://unpkg.com/networked-aframe/dist/networked-aframe.min.js"></script>
```

Hopefully that solves it.

Also, check out [this tutorial](https://github.com/haydenjameslee/networked-aframe/blob/master/docs/Tutorial:%20Create%20your%20first%20Networked-Aframe%20experience.md) on a good way to get started with Networked-Aframe.

Let me know if that doesn't solve it.

**Comment by pmccauley** [comment]
I ran into the exact same issue on a mac. Though I don't see anything about build.js in the file.  I'm using firefox nightly. Tracing back through to see If I am missing something.

**Comment by haydenjameslee** [comment]
Since its happening to a few people I'll change the examples so they don't use build.js soon.

**Comment by haydenjameslee** [comment]
The examples now use the unpkg reference instead of build.js: https://github.com/haydenjameslee/networked-aframe/commit/796984882a1d7b0bfc369d98729bc96a8606ffeb
